export const MANAGE_TABLE_HEADERS = [
  'ID',
  'Population ID', 
  'Name', 
  'Birthdate', 
  'Age',
  'Civil Status',
  'Relation to Family Head',
  'Educational Attainment',
  'Occupation',
  'Skills',
  'Employment Type',
  'Philhealth Number',
  'Monthly Income',
  'Health Status',
  'Remarks',
  'PWD ID',
  'Solo Parent ID',
  'Senior Citizen ID',
  'Actions'
];
